backend:
  name: github
  repo: Yutpatech/kodwebtr
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short description", name: "short", widget: "string"}
      - {
          label: 'Post Category',
          name: 'categories',
          widget: 'relation',
          collection: 'categories',
          searchFields: ['id, title'],
          valueField: 'id',
          displayFields: ['title'],
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'string'
        }
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
      - name: 'categories'
        label: 'Category'
        folder: 'content/categories'
        create: true
        slug: '{{slug}}'
        fields:
          - { label: 'Name', name: 'title', widget: 'string' }